apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
resources:
  - namespace.yaml
  - secret-exporter.sops.yaml
  - pv.yaml
  - pvc-media.yaml
  - pvc-config.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - exporter.yaml
