apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-exporter
    namespace: jellyfin
type: Opaque
stringData:
    JELLYFIN_TOKEN: ENC[AES256_GCM,data:y6oj4GzhQJVeB+EKwaLyz4USW+2GdcJK6SJJn5pwBl0BlA==,iv:+eSpgSoebEtVxnUAwcmQvAPcJz4nfpzVAQP8qE73/bo=,tag:6Rg/0Itq6+JbdKronXs75g==,type:str]
sops:
    age:
        - recipient: age1h5hafnt22aqn7uahcsmv5v8gfgwcxanypw0lantcush7jppt99fskz6vcv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQ3BTSlM4WkFPVGg3eDI4
            dG9mSHBZSXhkeEU1Q0JSOXVYaTIvSCsycms4CkMwM0ZyNW1YeHdnZi9NZmlYUG1r
            aFRsd3dEd1VxMERuQjlld2hmY0czbkkKLS0tIGZZYzhVTXFxaHZPT1Z1NHFGKzNt
            NU9JTG14UFAyTjVUSzNmak9JTjU1RU0KQ7I7PLFOP6+GFrvbHAKRZS7Y41km5gh3
            0PqwXwE9F9anzNq4MxpJR/5X7eqmOtyBbGkXfkKjrzVmanCcTrNdxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T10:54:06Z"
    mac: ENC[AES256_GCM,data:m/OAzVx2rZ/j6ASvG7gvuz+AoYDepKUL50axhBluClUyRvLiYwDfUxH5oU/eEglrVNfOERwUu+ktNnJ7OkIsNedpbQrSsD7GbrjxCOCdAl5R1LjXkb61CiJkn+ioI9B7LhL+Vbf+TeMO58sSj6V1kCjU0qN4qv1JlEl4l4g7Mbk=,iv:AcKZUjIsNCt0E8tqf76tgW9q64Pv49AhlE7GDzRdlTA=,tag:ISqRzFL+slqeyGm5MBA0VQ==,type:str]
    encrypted_regex: ^(data|stringData|spec)$
    version: 3.12.2
