apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-exporter
    namespace: jellyfin
type: Opaque
stringData:
    JELLYFIN_TOKEN: ENC[AES256_GCM,data:atGRPDCw/PwTmCT+LLhnYTFx7PHT0Yl36JoB8RVQcTU=,iv:TlYQtMHUU0g76/XQG+dXAM1H6ZAhAxHFGVgABkFTwDE=,tag:zD6q6cV4XLneEjVAXodWvw==,type:str]
sops:
    age:
        - recipient: age1h5hafnt22aqn7uahcsmv5v8gfgwcxanypw0lantcush7jppt99fskz6vcv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQ3BTSlM4WkFPVGg3eDI4
            dG9mSHBZSXhkeEU1Q0JSOXVYaTIvSCsycms4CkMwM0ZyNW1YeHdnZi9NZmlYUG1r
            aFRsd3dEd1VxMERuQjlld2hmY0czbkkKLS0tIGZZYzhVTXFxaHZPT1Z1NHFGKzNt
            NU9JTG14UFAyTjVUSzNmak9JTjU1RU0KQ7I7PLFOP6+GFrvbHAKRZS7Y41km5gh3
            0PqwXwE9F9anzNq4MxpJR/5X7eqmOtyBbGkXfkKjrzVmanCcTrNdxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T11:08:05Z"
    mac: ENC[AES256_GCM,data:xbVOJgToJh6AUM/XH6aX4dr0zpoVkaAeEiAllLDW7oRPuGSXPS4liEyeVGs5EPFjceS642Z3E69cKBVjq/HaG9M7RHKxY/laVKfoYLYxxPE4VZicMwdTtUoD+jN9/JUxSEMJdb06NogCHf1kf94vVovgceEzR3lcRI5segQtiAA=,iv:JDyNuMIGN8zcUYChl44mtQBkq1Cx17BxDx5ogZcSK1Y=,tag:AgUOiCNWn8Emsg/Qgl2QJg==,type:str]
    encrypted_regex: ^(data|stringData|spec)$
    version: 3.12.2
