# htpasswd lines for the basic-auth Middleware. bcrypt only (htpasswd -nB) —
# see middlewares.yaml.
apiVersion: v1
kind: Secret
metadata:
    name: basic-auth-users
    namespace: traefik
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:72X4IXa1FGSSPw6H+r5epq/3psv9l9OCcYLBOgsaGMPf3y6kQsWTz/Xcqh0Eep9fAvlIuykqh34mppx+AIo+qcs=,iv:vynqCLkbofu6sPzQMqAPVykBjov1ZFYCp68n/BHKbhc=,tag:cd9+nyNdoytSeczftQOVAg==,type:str]
sops:
    age:
        - recipient: age1h5hafnt22aqn7uahcsmv5v8gfgwcxanypw0lantcush7jppt99fskz6vcv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVzZQRnJhSU9QcHAvWkRK
            ZTlXbi9NNDVPOXBKNlg2emNPWkF6Y1BFZmlzClBmZlBkbXhSK1ZHcFY1aWRSZStM
            b0VlRGFMYWJ3dGltWi95MWQvenQwUncKLS0tICtBM1ZuUlpEMFdmcnRVOWRreHJR
            eWhnTkZpby91cEVyeUlFK1hNZ0owM00KH2BNks0Egk3ImVoAdNvgy5kUIdAaQ1u1
            cIJ3UQRhL8pgJ7XXYctJKauLdRt7PL4zlAjM0PUa3QolSdpPQ1LVBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T11:15:32Z"
    mac: ENC[AES256_GCM,data:dfn6NpWnrzPBpduKSDjdBBLzTOjc626oZnSekDlG1y40tC18qNdsIZL0XqCJgM1Tp0uerV2MuBe13juOdErjuPr2zdnVqj3YLH6OyaKibauF1DVLRqEyXLqmT2IDYu4eGd7yN60r0czuVQQcs534po185R1Jg75/ejTKhfe52rU=,iv:hTGJdgzQ7wFqk9u6ho+b0MBPlD7LEORiIGBFuXrrlYo=,tag:D0lHKXOkF4Z7ypfm+1ZMQg==,type:str]
    encrypted_regex: ^(data|stringData|spec)$
    version: 3.12.2
