proxmox_api_token: ENC[AES256_GCM,data:VNX4QiyVzBxu0ZD2N4euJzcdo2SN7nz6h1ji7QlV+CUhZDc4jYSvebDnKmPMuUszv2O7U+iD4Q==,iv:zYVhBsUpe56ftx2jsCLFlqrVk/BD2nmt8gjXHMcuhDY=,tag:vIvW+fCA78T02KU9T4rFkQ==,type:str]
pve_exporter_token: ENC[AES256_GCM,data:59xddcMHi22LTRvaUQiSORa7vUl5tPnhA5i/Bfgenzi7IExSau4FqV6yBwQaehCj7hZxjA==,iv:7siqD0fKq3UX+tJeWPZ4zR6DceQNNebpyE/S5LPTDCs=,tag:J+IR2yg/tuJ9TsvCIebc+Q==,type:str]
sops:
    age:
        - recipient: age1h5hafnt22aqn7uahcsmv5v8gfgwcxanypw0lantcush7jppt99fskz6vcv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBya2VzUmFCY2MwcDg0cnRm
            eXE4M0sxZS9xcXlsT1lVWGhNaVFtSm40WXdVCkpYajFscDJ5cHVnZHlydmNMR0ZC
            NDJKVmF5ckJ1MVlGVlNha0E2aU9wMVUKLS0tIHlmVkZnRUhmbG5pYjdma2tTVEE3
            SGtHNTl5d3ZnSGJ2OG4xMVNNNzN6K0UKpsFVlQv19kt2nwlO44N/kw69mjxN7h4a
            Aso+RvUAaPiCu1GFvS7fOW+8ar9OUErXmUH7RjuswrgP5wF2jA/Wzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-17T10:14:24Z"
    mac: ENC[AES256_GCM,data:MtFr1B/O2qscCKezO8Mu8yhwygv4qDXdKARxoPURQ6DvNDFWvJ488z1jlPbPo7tGXsFAIIgboxIh8xf7Xf5PHsFtvnOCbFEC+kJXEovRBqYB+qdfhYNqJViCs/roTjkwEz81/NsVfociitKAemeURJ+zsLEGN01Qq0BoOfyxk4Y=,iv:uVnK6L801TbimQTKM1/PljwVvnEcd7LBwAdyg/h531c=,tag:pjpafAhWc8103MnqdOoLgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
