# The Pi-hole web password (the value tofu's pihole/secrets.env sets).
apiVersion: v1
kind: Secret
metadata:
    name: pihole-exporter
    namespace: host-monitoring
    annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
type: Opaque
stringData:
    PIHOLE_PASSWORD: ENC[AES256_GCM,data:TdFdDJn0qgwZYg==,iv:6zP7MY4PcRL4lESyHfiB6ztczBMmlr98fG+910wnWDQ=,tag:jF9yjRogv9+9XNSeuFdVhg==,type:str]
sops:
    age:
        - recipient: age1h5hafnt22aqn7uahcsmv5v8gfgwcxanypw0lantcush7jppt99fskz6vcv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3c3BpSXhxaDhLSDNPUDdS
            Z2VBZ1BNVERQd0R1ZTFZOU5WR05FNWx0RUFBCjhkS0tkQmkzR0lHS1ZxWjBGaURI
            SzhhVVk2Q0d5cHBpN2NVSWN3UEVWeEEKLS0tIDIwNzlwQ3JtWjM2Uy9OUkhIMDEw
            cFZyQ2VNa3hUbTdoTVdlZ1l0cml5Wm8KdjW8gFZ6OqG16+S2s4Hsx02ojvSeSm0Z
            GJWcX4jcuSJOE0w+S97zlsPUsssjqDh5JE0X4+5qxFViJQ/Wh0arrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T13:09:55Z"
    mac: ENC[AES256_GCM,data:tzaLBWA2DR8HFArBHqeZMq2ua1YrisR8OpfHAcR1JrYjxS5Q12D9fB8qeDgA1Bgmn1tuO0ikQD+SOfk4dyE29hD3IfxeE0xge8z0lXTmaRb/vjMCsMbR0sJBt+nu4gE4c9ClegbjQqXcirGn4abf3Q8kJdzmwebxJNrW1swoqoY=,iv:lh7gfw2o83rtwnHNeNE3Ztu9/CL2K4fpDEyvM8k518g=,tag:C7jup3vikwCirXeQcMMe3Q==,type:str]
    encrypted_regex: ^(data|stringData|spec)$
    version: 3.12.2
