# The Pi-hole web password (the value tofu's pihole/secrets.env sets).
apiVersion: v1
kind: Secret
metadata:
    name: pihole-exporter
    namespace: host-monitoring
    annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
type: Opaque
stringData:
    PIHOLE_PASSWORD: ENC[AES256_GCM,data:oVLFlctyu9hPXdu9+k1L2N5yDtvKzuT6fw5LK7PxK9g=,iv:yYaFjO1oNURVLBMjwWxxgXp98lel/69hTO42r7/SLSk=,tag:F92AYWhETRr0bpxEAusOCg==,type:str]
sops:
    age:
        - recipient: age1h5hafnt22aqn7uahcsmv5v8gfgwcxanypw0lantcush7jppt99fskz6vcv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3c3BpSXhxaDhLSDNPUDdS
            Z2VBZ1BNVERQd0R1ZTFZOU5WR05FNWx0RUFBCjhkS0tkQmkzR0lHS1ZxWjBGaURI
            SzhhVVk2Q0d5cHBpN2NVSWN3UEVWeEEKLS0tIDIwNzlwQ3JtWjM2Uy9OUkhIMDEw
            cFZyQ2VNa3hUbTdoTVdlZ1l0cml5Wm8KdjW8gFZ6OqG16+S2s4Hsx02ojvSeSm0Z
            GJWcX4jcuSJOE0w+S97zlsPUsssjqDh5JE0X4+5qxFViJQ/Wh0arrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T17:52:37Z"
    mac: ENC[AES256_GCM,data:gcUGscscOuiEpWHY7lDtFFCxUc0+UTGqAq8VGGhdYR+H3iQMXEwthunAyig9Wr39ZBZhZqoFPQ0x0W8pQZTrFyNwokq/WBYjS/ppMrOPrasEGS4FezKOohjEWYfHzFalXA3TEyGZNR43SM6VOal2v5Jut3uYrEyGxwrYHIeGMMM=,iv:7BzIUE0eENACMitqFnF6uU7MdlZlBtBSxVVx11P3cfE=,tag:Erv0CJ8AiSUlxwbdthsDpw==,type:str]
    encrypted_regex: ^(data|stringData|spec)$
    version: 3.12.2
