apiVersion: v1
kind: Secret
metadata:
    name: searxng
    namespace: searxng
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:FcP3vT2n7WNL2P8pCAy3oYUmev4xykEYXVZdXhZB/MqxGQhjZJbiRsjjQVu1zAtZx8rIU3BGHoBczx6RLUeCRw==,iv:QlGa2waYmDcKWgjDaKNdAI631rWFp6arfrABCv2zrew=,tag:X8V4TIG3vESRt1ODyfc3MQ==,type:str]
sops:
    age:
        - recipient: age1h5hafnt22aqn7uahcsmv5v8gfgwcxanypw0lantcush7jppt99fskz6vcv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUXo1dzFmbXRESi9HSjdr
            c3lTbkV0RzZxeTlTRGh4WTZOQjluM3dzMERVCkxqR0RneVZ1NldKZEVMZUNxM2FD
            L2w3VHpSb3RHT0oxZFZnZy8xa1gzTFkKLS0tIFZzaW93cnU4NVp2WHhpMjdPZ1pZ
            WUN3aFhEeW5zMGVxMGpGa3A3Qkt2MnMKR3m/KdrKwr/bD/ERy9Vsaa4swGVb2WyE
            s2xiYmK1vIMmlvFjVHBduwC3gGcVKLWBQWntWHtEUeBTZ+64GmO8Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-17T16:15:46Z"
    mac: ENC[AES256_GCM,data:9pqbaGmPTWsJYxNZcaK1SIym6YxvgLMvG3Lp6l3q+sP/MLGdjGg2NN5gRv6jDeGVKta/FPfT//6kl/W8nXHeNgDh0ISnoAN7DdbX70yj06XUy5s9jR+IXsyGrtuU1REUusSxlGZCFgKAatMjK39VscY3CczPcrqiP5vdN47N6qU=,iv:e5KZIu6VAch4eTnyb/6fiy6B2iYeJyI9Jx8eg6Mju5o=,tag:9JD3ZyOop6LdISQVo2njCg==,type:str]
    encrypted_regex: ^(data|stringData|spec)$
    version: 3.12.2
