---
services:
  dnsmasq:
    image: jpillora/dnsmasq:1.1
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pxe-config/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./tftp:/var/tftp:ro
    restart: unless-stopped

  caddy:
    image: caddy:2.8
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./http:/srv/http:ro
    restart: unless-stopped
