---
- name: Start PXE server.
  hosts: localhost
  connection: local
  # Facts needed: ansible_default_ipv4.{network,netmask,gateway,address}
  gather_facts: true
  roles:
    - 00-pxe

- name: Wake target machines and wait for them to come online.
  hosts: pxe
  gather_facts: false
  roles:
    - 01-wake-on-lan
