apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    DOMAIN: ENC[AES256_GCM,data:UIb8qRGZ+yLe+j0=,iv:Pdrz8PKROcmL7QGv331UTlmdPzSfZ6oYUWTRKgUrBbI=,tag:3AS05ihS5YBPsJiqUGUdvQ==,type:str]
    TRAEFIK_LB_IP: ENC[AES256_GCM,data:XwfLqWMikoEUpQ==,iv:NLOLeRFz0mX6uffzybYJNx6Lvz0szWUoqCO4kq+neSc=,tag:TK7s7GC04Sqwosmi6Nj83g==,type:str]
    ACME_EMAIL: ENC[AES256_GCM,data:NYw+42iQHW4p5ogTyarviDbws0Wl28FePgfpHc/qhw2hqEE6p4sk,iv:Hx7JOb+qd9sW6R07gQ2DQf8m/Z837qBkjRziKp1Zp8s=,tag:RhPh6RT/rT4KgQLy8wRWaA==,type:str]
    RUMBA_IP: ENC[AES256_GCM,data:QkHSHAMYMEVA1Q==,iv:6gqY841thIv45ZL1fnP1lOg5Kn+zpleYwx+52yrxWQw=,tag:X9W/Mh0cmTCqs6rcYcebxA==,type:str]
    TANGO_IP: ENC[AES256_GCM,data:apc/HDhQf1JJ3g==,iv:HeDgZexx6HEa8wgIdBd0BleOhxVxkXjjIQ56TMzpHls=,tag:LIO+TCvvVVgk96Cplfzyow==,type:str]
    SALSA_IP: ENC[AES256_GCM,data:7j+NMlwxb708+A==,iv:+x26PVqPPc9Ign5oPvtgp6ydOg85iEVs+k/VU7aq67M=,tag:Eu1aI+GIl2Fr1pLfqzGTLQ==,type:str]
    SAMBA_IP: ENC[AES256_GCM,data:6QxTlZR/qsKVkA==,iv:3w4PgerIPYYXwPrqde7c4HjxgTJY8NRexUzMwJ0c14w=,tag:xwI16cthSw3eqUucbgVgsw==,type:str]
    VOYAGER_IP: ENC[AES256_GCM,data:TBEpqKLDrYtNiQ==,iv:runFjH7fc2taMqgjqG5RvyW9QsvLe5WJ3JYTKhuHj5o=,tag:tIANApJeD/wvFzHIRVmBoQ==,type:str]
    PIHOLE_IP: ENC[AES256_GCM,data:8lQuaiS/GcY=,iv:szxa98FX7kE/+cDD75ouCxKo2XPWMjnBEjOiPHHKwuo=,tag:HGZTo0kKKb+I8eW3DLdzFg==,type:str]
    ROUTER_IP: ENC[AES256_GCM,data:XJGgwiPQE24=,iv:VT27h1VZ6aH+VusB9u68eYhz6vEY6WazFolLQEYjBNA=,tag:WA5mpfATCaQ4gDUp9fk3CA==,type:str]
    INGEST_LB_IP: ENC[AES256_GCM,data:Yvf5xwjXcBG+Nw==,iv:m8CoWx3qouRjJ1v4L7+RfWiLJdfgfDg8we06zM969bg=,tag:A7+XoAR4NWUPy1sGX8Zzfg==,type:str]
    SEARXNG_OPEN_METRICS: ENC[AES256_GCM,data:Y/V44b0dpu/A2vcn52U5AFEChFRA4p954sknE7iwNahD6ARnwbe0ptRBKhuQO4qG,iv:E+NUBL1ajcc9fEyVosTkz1k3TjNOr1Sk9Dg9MIrcWgQ=,tag:vdgGXCaOPOI4ACsqsz3K5Q==,type:str]
    NETBOX_URL: ENC[AES256_GCM,data:VtraE9uqLd43G5koRsdQ8+65T890Akb8gJU=,iv:KON331z+nthIo9xMvFdh7+sph6eeysAffM+Dxg0EAYc=,tag:+Glf8aPqZ2XIvktZa42L0Q==,type:str]
    HOME_ASSISTANT_LB_IP: ENC[AES256_GCM,data:5ZTwx+fUU3fzNQ==,iv:kUE5taOOxxrKYSeA7rUXSsKnIupGy3wS/OpaqwCfaNc=,tag:byGM4Fhm3lXvvsIRyVHXRQ==,type:str]
    HOME_ASSISTANT_TOKEN: ENC[AES256_GCM,data:wrK9Xt2gp+bfZZwZ0/jhEomgM0XMxsVWK4KCJtDKE+aYvhSL4ucMAA0xv8I6H9rob/FZqX+n3EsxSnU+xPKPGAvlvUzxSuEOCP2zsPL3FW1p1q/RrWPNPdBPUO5jz4QIXLBEEwgQStapHBdNx67znMuFnQBbXn9V5BdAqslykwN4QQM1pOg+nWQ6Vx+aEI6CBvgkCUIIAZHKtnzWcCoCjoQIC+rwjv2yPVMCgc2JCcdpDAB2FIwc,iv:Ce34sHTlZjuN8M2z74CSJsTk4GCbbUtgkhyw/vATENo=,tag:1p2aW5o4krp0yu/KAk7Gig==,type:str]
sops:
    age:
        - recipient: age1h5hafnt22aqn7uahcsmv5v8gfgwcxanypw0lantcush7jppt99fskz6vcv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2R2R2aEluVE5LVUNOR1ph
            RnV0d3IvaVFYOVRRQm5IeFZ5b3hTMU9BQmp3ClpMMWhYK3k2Z2hNN29RUnRtSXpZ
            eTlTbjNBRHRlclJhQ2JJaVNMV2l3bXMKLS0tIG02cXhOUldacWQwQTNTaitXSXFT
            dDRoNGJHVUd0U29aS3JUaUlzNnhCTXcKsJLU+jHIvkEiUwEOEVe5ayt9sFdk+krh
            Q/q4QvcqEq0d5j2ivfv9g3QAeQ2dKdRZRn+hBc0IThJ+dOCFeI52UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T11:37:58Z"
    mac: ENC[AES256_GCM,data:l37w/Ren6Ok8lHDxWpNkC1HdunbpknlOU1RKkDGAwnGNen14eQMc+P8QH846gTvzpMG0C4M8cPsIE4CXsm6xfdgKLTrgmWbkpHUKcOaeLN2Nvv+doOD5GU8vcDP1orjg5beqXJOxhdxsvpQ5BD0jjFHDIFzsoJjcyqQCYbLNTKc=,iv:a2VLwFh1nkF/T24WWStBcICsm4RZP6OOflu7pCXajzc=,tag:TYBg7nyCMTEA5vbJDxTS0w==,type:str]
    encrypted_regex: ^(data|stringData|spec)$
    version: 3.12.2
