apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    DOMAIN: ENC[AES256_GCM,data:UIb8qRGZ+yLe+j0=,iv:Pdrz8PKROcmL7QGv331UTlmdPzSfZ6oYUWTRKgUrBbI=,tag:3AS05ihS5YBPsJiqUGUdvQ==,type:str]
    TRAEFIK_LB_IP: ENC[AES256_GCM,data:XwfLqWMikoEUpQ==,iv:NLOLeRFz0mX6uffzybYJNx6Lvz0szWUoqCO4kq+neSc=,tag:TK7s7GC04Sqwosmi6Nj83g==,type:str]
    ACME_EMAIL: ENC[AES256_GCM,data:NYw+42iQHW4p5ogTyarviDbws0Wl28FePgfpHc/qhw2hqEE6p4sk,iv:Hx7JOb+qd9sW6R07gQ2DQf8m/Z837qBkjRziKp1Zp8s=,tag:RhPh6RT/rT4KgQLy8wRWaA==,type:str]
    RUMBA_IP: ENC[AES256_GCM,data:QkHSHAMYMEVA1Q==,iv:6gqY841thIv45ZL1fnP1lOg5Kn+zpleYwx+52yrxWQw=,tag:X9W/Mh0cmTCqs6rcYcebxA==,type:str]
    TANGO_IP: ENC[AES256_GCM,data:apc/HDhQf1JJ3g==,iv:HeDgZexx6HEa8wgIdBd0BleOhxVxkXjjIQ56TMzpHls=,tag:LIO+TCvvVVgk96Cplfzyow==,type:str]
    SALSA_IP: ENC[AES256_GCM,data:7j+NMlwxb708+A==,iv:+x26PVqPPc9Ign5oPvtgp6ydOg85iEVs+k/VU7aq67M=,tag:Eu1aI+GIl2Fr1pLfqzGTLQ==,type:str]
    SAMBA_IP: ENC[AES256_GCM,data:6QxTlZR/qsKVkA==,iv:3w4PgerIPYYXwPrqde7c4HjxgTJY8NRexUzMwJ0c14w=,tag:xwI16cthSw3eqUucbgVgsw==,type:str]
    VOYAGER_IP: ENC[AES256_GCM,data:TBEpqKLDrYtNiQ==,iv:runFjH7fc2taMqgjqG5RvyW9QsvLe5WJ3JYTKhuHj5o=,tag:tIANApJeD/wvFzHIRVmBoQ==,type:str]
    PIHOLE_IP: ENC[AES256_GCM,data:8lQuaiS/GcY=,iv:szxa98FX7kE/+cDD75ouCxKo2XPWMjnBEjOiPHHKwuo=,tag:HGZTo0kKKb+I8eW3DLdzFg==,type:str]
    ROUTER_IP: ENC[AES256_GCM,data:XJGgwiPQE24=,iv:VT27h1VZ6aH+VusB9u68eYhz6vEY6WazFolLQEYjBNA=,tag:WA5mpfATCaQ4gDUp9fk3CA==,type:str]
    INGEST_LB_IP: ENC[AES256_GCM,data:Yvf5xwjXcBG+Nw==,iv:m8CoWx3qouRjJ1v4L7+RfWiLJdfgfDg8we06zM969bg=,tag:A7+XoAR4NWUPy1sGX8Zzfg==,type:str]
sops:
    age:
        - recipient: age1h5hafnt22aqn7uahcsmv5v8gfgwcxanypw0lantcush7jppt99fskz6vcv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2R2R2aEluVE5LVUNOR1ph
            RnV0d3IvaVFYOVRRQm5IeFZ5b3hTMU9BQmp3ClpMMWhYK3k2Z2hNN29RUnRtSXpZ
            eTlTbjNBRHRlclJhQ2JJaVNMV2l3bXMKLS0tIG02cXhOUldacWQwQTNTaitXSXFT
            dDRoNGJHVUd0U29aS3JUaUlzNnhCTXcKsJLU+jHIvkEiUwEOEVe5ayt9sFdk+krh
            Q/q4QvcqEq0d5j2ivfv9g3QAeQ2dKdRZRn+hBc0IThJ+dOCFeI52UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T17:46:50Z"
    mac: ENC[AES256_GCM,data:vU9uBJLad9VopnoOm50U6kHDlbJz2C0gpZj+a7cQC8I5ZfYAb+fdwanTx0kFLPSb06QmKbC2Lpl7sDcTj/v1A/pLmaY/yth77rj1hi3bU1vFNcFWBrmsXdmq+U8O4akaUTcJhl1RsprYOJHX9nKqqjj09en8SZlGYMZodn3tN/0=,iv:RVmc4ku/o4Ovgf9PgUroq4xjPcrsHsVE7VZyAFI4o7M=,tag:VKTWNNfdOZHRTjEIMdUFxQ==,type:str]
    encrypted_regex: ^(data|stringData|spec)$
    version: 3.12.2
