apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    DOMAIN: ENC[AES256_GCM,data:UIb8qRGZ+yLe+j0=,iv:Pdrz8PKROcmL7QGv331UTlmdPzSfZ6oYUWTRKgUrBbI=,tag:3AS05ihS5YBPsJiqUGUdvQ==,type:str]
    TRAEFIK_LB_IP: ENC[AES256_GCM,data:XwfLqWMikoEUpQ==,iv:NLOLeRFz0mX6uffzybYJNx6Lvz0szWUoqCO4kq+neSc=,tag:TK7s7GC04Sqwosmi6Nj83g==,type:str]
    ACME_EMAIL: ENC[AES256_GCM,data:NYw+42iQHW4p5ogTyarviDbws0Wl28FePgfpHc/qhw2hqEE6p4sk,iv:Hx7JOb+qd9sW6R07gQ2DQf8m/Z837qBkjRziKp1Zp8s=,tag:RhPh6RT/rT4KgQLy8wRWaA==,type:str]
sops:
    age:
        - recipient: age1h5hafnt22aqn7uahcsmv5v8gfgwcxanypw0lantcush7jppt99fskz6vcv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2R2R2aEluVE5LVUNOR1ph
            RnV0d3IvaVFYOVRRQm5IeFZ5b3hTMU9BQmp3ClpMMWhYK3k2Z2hNN29RUnRtSXpZ
            eTlTbjNBRHRlclJhQ2JJaVNMV2l3bXMKLS0tIG02cXhOUldacWQwQTNTaitXSXFT
            dDRoNGJHVUd0U29aS3JUaUlzNnhCTXcKsJLU+jHIvkEiUwEOEVe5ayt9sFdk+krh
            Q/q4QvcqEq0d5j2ivfv9g3QAeQ2dKdRZRn+hBc0IThJ+dOCFeI52UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T11:13:55Z"
    mac: ENC[AES256_GCM,data:x1tloGiQjGUDo1gAac/LBHncqaysUdhhppdvlMoP5oyu+uinmWorFeXPlxC6lUI2mmoCofb4S6/EwB99/YTWHuve7jL1jP70byCf+nhyOILzUnIedXnbdkbdjb+XWhjL40fwYT5Cii8kl65/QQvuBVZDGGACpRfsRJl5PZhiors=,iv:CZ/tlhiBMuRPOpsXz8l/ubapIRfanUxt8k/h5UnuSoM=,tag:rpkCr7K2ChawIvo9V33zqw==,type:str]
    encrypted_regex: ^(data|stringData|spec)$
    version: 3.12.2
